name = "wcc"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["WCC"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "WCC"
